//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 07:05:57 PM IST 
//


package com.example.FlightSearch.ndcDomainModel.pojo;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Requests the airline to additionally include a preview of the Offer price for the same Shopping Criteria for the specified date range.
 * 
 * <p>Java class for CalendarDateCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalendarDateCriteriaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DaysAfterNumber" type="{http://www.iata.org/IATA/2015/00/2019.2/IATA_AirShoppingRQ}NumberType" minOccurs="0"/>
 *         &lt;element name="DaysBeforeNumber" type="{http://www.iata.org/IATA/2015/00/2019.2/IATA_AirShoppingRQ}NumberType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalendarDateCriteriaType", propOrder = {
    "daysAfterNumber",
    "daysBeforeNumber"
})
public class CalendarDateCriteriaType {

    @XmlElement(name = "DaysAfterNumber")
    protected BigDecimal daysAfterNumber;
    @XmlElement(name = "DaysBeforeNumber")
    protected BigDecimal daysBeforeNumber;

    /**
     * Gets the value of the daysAfterNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDaysAfterNumber() {
        return daysAfterNumber;
    }

    /**
     * Sets the value of the daysAfterNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDaysAfterNumber(BigDecimal value) {
        this.daysAfterNumber = value;
    }

    /**
     * Gets the value of the daysBeforeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDaysBeforeNumber() {
        return daysBeforeNumber;
    }

    /**
     * Sets the value of the daysBeforeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDaysBeforeNumber(BigDecimal value) {
        this.daysBeforeNumber = value;
    }

}
