//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 07:05:57 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.iata.org/IATA/2015/00/2019.2/IATA_AirShoppingRQ", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.FlightSearch.ndcDomainModel.pojo;
